Use ES6 modules to write modular JavaScript
elad237/awesome-book-ES6 pull request #2
Opened 2023-01-16 16:28 UTC by elad237

In this project, I was able to restructure the Awesome books app code. The goal is to make it more organized by using modules. .

2023-01-16 17:35 UTC, Gambit142 requested changes
Hi @elad237 👋, 

Great work on making the changes requested by a previous reviewer 👏 

Hi @elad237 👋, 

Good job so far!

## Highlights
- There are an index.js file, an index.html and index.js files✔️ 
- Good use of JavaScript `modules` ✔️ 
- Good use of arrow functions ✔️ 
- Good use of `let` and `const` keywords ✔️  

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

- You can also consider the suggestion tagged [OPTIONAL] under this review. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-16 17:35 UTC, Gambit142 commented on README.md
> +
- [ ] Kindly remove the Microverse logo from this file. If you have your customized logo, you can use it, but if you don't, kindly remove it. 👍

2023-01-16 17:35 UTC, Gambit142 commented on index.js
> +
- [ ] Kindly remove this Eslint disabling comment from this file. `Eslint` helps us to write clean, maintainable and readable codes. Using Eslint disabling comments defeats this purpose. Kindly remove it. 👍

2023-01-16 17:35 UTC, Gambit142 commented on modules/StoreClass.js
> +  }
- [OPTIONAL] It would be a good UI design to display a message that tells users if books have been added when they click the _**Add**_ button. 👍

2023-01-17 11:25 UTC, julie-ify approved these changes
Hi @elad237,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 15:37 UTC, merged